server:
  port: 8080
  error:
    path: /error
#  ssl:
#    key-alias: localhost
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: android
#    key-store-type: PKCS12


line:
  clientId: kFulu7Km2yIyafaYg97AfJ
  clientSecret: G5Pd7FrjGZGLy9PhrwnplP26vkCDqdzuiUzGBBeX27W
  clientReturnUrl: http://localhost:8080/front/linenotify
spring:
  application:
    name: reggie_take_out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Taipei&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 5ms
        max-idle: 4
        min-idle: 0
  cache:
    redis:
      time-to-live: 3600000
  data:
    redis:
      repositories:
        enabled: false
demo:
  path: D:/upload/
